# SQL ORDER BY (ASC & DESC)

Real-world table creation, data insertion, and sorting

## 1. Load SQL Extension

In [3]:
%load_ext sql

## 2. Connect to Database

In [8]:
%sql postgresql://localhost/sql_for_ds

## 3. Create Real-World Table: sales

In [9]:
%%sql
CREATE TABLE sales (
    sale_id INTEGER PRIMARY KEY,
    product_name TEXT,
    category TEXT,
    price INTEGER,
    quantity INTEGER,
    sale_date DATE
);

 * postgresql://localhost/sql_for_ds
Done.

[]

## 4. Insert Real-World Data

In [10]:
%%sql
INSERT INTO sales VALUES
(1, 'Laptop', 'Electronics', 75000, 2, '2024-01-10'),
(2, 'Phone', 'Electronics', 30000, 5, '2024-01-12'),
(3, 'Shoes', 'Fashion', 4000, 10, '2024-01-15'),
(4, 'Watch', 'Accessories', 8000, 3, '2024-01-18'),
(5, 'Headphones', 'Electronics', 2000, 7, '2024-01-20'),
(6, 'T-shirt', 'Fashion', 1200, 15, '2024-01-22');

 * postgresql://localhost/sql_for_ds
6 rows affected.

[]

## 5. ORDER BY ASC (Low to High)

In [11]:
%%sql
SELECT * FROM sales ORDER BY price ASC;

 * postgresql://localhost/sql_for_ds
6 rows affected.

[(6, 'T-shirt', 'Fashion', 1200, 15, datetime.date(2024, 1, 22)),
 (5, 'Headphones', 'Electronics', 2000, 7, datetime.date(2024, 1, 20)),
 (3, 'Shoes', 'Fashion', 4000, 10, datetime.date(2024, 1, 15)),
 (4, 'Watch', 'Accessories', 8000, 3, datetime.date(2024, 1, 18)),
 (2, 'Phone', 'Electronics', 30000, 5, datetime.date(2024, 1, 12)),
 (1, 'Laptop', 'Electronics', 75000, 2, datetime.date(2024, 1, 10))]

## 6. ORDER BY DESC (High to Low)

In [13]:
%%sql
SELECT * FROM sales ORDER BY price DESC;

 * postgresql://localhost/sql_for_ds
6 rows affected.

[(1, 'Laptop', 'Electronics', 75000, 2, datetime.date(2024, 1, 10)),
 (2, 'Phone', 'Electronics', 30000, 5, datetime.date(2024, 1, 12)),
 (4, 'Watch', 'Accessories', 8000, 3, datetime.date(2024, 1, 18)),
 (3, 'Shoes', 'Fashion', 4000, 10, datetime.date(2024, 1, 15)),
 (5, 'Headphones', 'Electronics', 2000, 7, datetime.date(2024, 1, 20)),
 (6, 'T-shirt', 'Fashion', 1200, 15, datetime.date(2024, 1, 22))]

## 7. ORDER BY Multiple Columns

In [14]:
%%sql
SELECT * FROM sales ORDER BY category ASC, price DESC;

 * postgresql://localhost/sql_for_ds
6 rows affected.

[(4, 'Watch', 'Accessories', 8000, 3, datetime.date(2024, 1, 18)),
 (1, 'Laptop', 'Electronics', 75000, 2, datetime.date(2024, 1, 10)),
 (2, 'Phone', 'Electronics', 30000, 5, datetime.date(2024, 1, 12)),
 (5, 'Headphones', 'Electronics', 2000, 7, datetime.date(2024, 1, 20)),
 (3, 'Shoes', 'Fashion', 4000, 10, datetime.date(2024, 1, 15)),
 (6, 'T-shirt', 'Fashion', 1200, 15, datetime.date(2024, 1, 22))]

## 8. Convert to Pandas

In [16]:
import pandas as pd
result = %sql SELECT * FROM sales;
df = result.DataFrame()
df.head()

 * postgresql://localhost/sql_for_ds
6 rows affected.

   sale_id product_name     category  price  quantity   sale_date
0        1       Laptop  Electronics  75000         2  2024-01-10
1        2        Phone  Electronics  30000         5  2024-01-12
2        3        Shoes      Fashion   4000        10  2024-01-15
3        4        Watch  Accessories   8000         3  2024-01-18
4        5   Headphones  Electronics   2000         7  2024-01-20

## 9. Pandas Sorting

In [17]:
df.sort_values(by='price', ascending=True)

   sale_id product_name     category  price  quantity   sale_date
5        6      T-shirt      Fashion   1200        15  2024-01-22
4        5   Headphones  Electronics   2000         7  2024-01-20
2        3        Shoes      Fashion   4000        10  2024-01-15
3        4        Watch  Accessories   8000         3  2024-01-18
1        2        Phone  Electronics  30000         5  2024-01-12
0        1       Laptop  Electronics  75000         2  2024-01-10

In [18]:
df.sort_values(by='price', ascending=False)

   sale_id product_name     category  price  quantity   sale_date
0        1       Laptop  Electronics  75000         2  2024-01-10
1        2        Phone  Electronics  30000         5  2024-01-12
3        4        Watch  Accessories   8000         3  2024-01-18
2        3        Shoes      Fashion   4000        10  2024-01-15
4        5   Headphones  Electronics   2000         7  2024-01-20
5        6      T-shirt      Fashion   1200        15  2024-01-22